on:
  push:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Configure rust to build wasm
        run: rustup target add wasm32-wasi

      - name: Build wasm binary
        run: cargo build --target wasm32-wasi --release

      - name: Deploy to test
        run: npx wrangler@wasm publish --env test target/wasm32-wasi/release/new-uuid.wasm
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Test deployment to test
        run: sleep 5s && curl --fail https://test.new-uuid.com

      - name: Deploy to prod
        run: npx wrangler@wasm publish target/wasm32-wasi/release/new-uuid.wasm
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Test deployment to prod
        run: sleep 5s && curl --fail https://new-uuid.com
